// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:151046119473:web:9ac2f9182addbd97daf510',
    messagingSenderId: '151046119473',
    projectId: 'residex-2ebd8',
    authDomain: 'residex-2ebd8.firebaseapp.com',
    storageBucket: 'residex-2ebd8.firebasestorage.app',
    measurementId: 'G-73CPY1C5KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:472430821939:android:754de13913884a47139946',
    messagingSenderId: '472430821939',
    projectId: 'residex-2ebd8',
    storageBucket: 'residex-2ebd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:151046119473:ios:7cb3648671d279c7daf510',
    messagingSenderId: '151046119473',
    projectId: 'residex-2ebd8',
    storageBucket: 'residex-2ebd8.firebasestorage.app',
    iosBundleId: 'com.residex.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:151046119473:ios:8f72825e6c5a27b9daf510',
    messagingSenderId: '151046119473',
    projectId: 'residex-2ebd8',
    storageBucket: 'residex-2ebd8.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:151046119473:web:867ae8b31a83c206daf510',
    messagingSenderId: '151046119473',
    projectId: 'residex-2ebd8',
    authDomain: 'residex-2ebd8.firebaseapp.com',
    storageBucket: 'residex-2ebd8.firebasestorage.app',
    measurementId: 'G-F5FGHMT502',
  );
}
